about/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name='app_about'
urlpatterns = [
    path("", views.index,name='about')
]

contact/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name='app_contact'
urlpatterns = [
    path("", views.index,name='contact')
]

newweb/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='app_home'
urlpatterns = [
    path("admin/", admin.site.urls),
    path("",views.index,name='home'),
    path("about/",include('about.urls')),
    path("skill",include('skill.urls')),
    path("services",include('services.urls')),
    path("project",include('project.urls')),
    path("contact", include ('contact.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name='app_project'
urlpatterns = [
    path("", views.indexView.as_view(),name='project'),
    path("detail/<slug:slug>", views.detail, name='detail'),
    path('category-<str:category>/',
         views.indexView.as_view(), name='projects_category'),
    path('page-<int:page>/', views.indexView.as_view(), name='project_page'),
]

services/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name='app_services'
urlpatterns = [
    path("", views.index,name='services')
]

skill/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name='app_skill'
urlpatterns = [
    path("", views.index,name='skill')
]

about/models.py
from django.db import models

# Create your models here.
class summaries(models.Model):
    isi=models.TextField()
    

contact/models.py
from django.db import models

# Create your models here.
class ContactModel(models.Model):
    name= models.CharField(max_length=50)
    email=models.EmailField()
    call= models.CharField(max_length=20)
    locations = models.CharField(max_length=50)
    subject = models.CharField(max_length=50) 
    message = models.CharField(max_length=500)

    def __str__(self):
        return "{}".format(self.name)

project/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from multiselectfield import MultiSelectField

# create your models here.


class Proyek(models.Model):
    ITEM_CHOICES = [
        ('Excel','Excel'),
        ('SQL', 'SQL'),
        ('Power-BI', 'Power BI'),
        ('Tableau', 'Tableau'),
        ('Streamlit', 'Streamlit'),
        ('Python', 'Python'),
        ('Django', 'Django')
    ]
    id = models.AutoField(primary_key=True)
    nama = models.CharField(max_length=250)
    category = MultiSelectField(choices=ITEM_CHOICES, max_length=250)
    gambar = models.ImageField(upload_to='media', blank=True)
    gambar2 = models.ImageField(upload_to='media', blank=True)
    gambar3 = models.ImageField(upload_to='media', blank=True)
    gambar4 = models.ImageField(upload_to='media', blank=True)
    tanggal = models.DateField(default=timezone.now)
    client = models.CharField(max_length=55)
    output = models.URLField(default='a')
    detail = models.URLField(default='a')
    embed= models.TextField(blank=True, max_length=500)
    slug = models.SlugField(blank=True, editable=False)


    def __str__(self):
        return "{} - {}".format(self.nama, self.category)
    
    def save(self):
        self.slug = slugify(self.nama)
        super(Proyek, self).save()
            

services/models.py
from django.db import models


class offer(models.Model):
    item = models.CharField(max_length=30)
    desc = models.TextField()
    icon = models.CharField(max_length=100)

    def __str__(self):
        return "{}".format(self.item)

skill/models.py
from django.db import models

# Create your models here.


class listskill(models.Model):
    name_skill = models.CharField(max_length=50)
    image = models.ImageField(upload_to='img')

    def __str__(self):
        return self.name_skill

about/views.py
from django.shortcuts import render
from .models import summaries

# Create your views here.
def index(request):
    summarry=summaries.objects.all()
    context={
        'title':'About me',
        'summary':summarry
    }
    return render(request,'about/index.html',context)

contact/views.py
from django.shortcuts import render
from .models import ContactModel

# Create your views here.
def index(request):
    contact= ContactModel.objects.all()
    context={
        'title':'Contact',
    }
    return render(request,'contact/index.html',context)

newweb/views.py
from django.shortcuts import render

def index(request):
    return render(request,'index.html')

project/views.py
from django.shortcuts import render,get_object_or_404
from .models import Proyek
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView

# Create your views here.
# def index(request):
#     proyeks= Proyek.objects.all()
#     paginator= Paginator(proyeks,5)
#     page_number= request.GET.get('page')
#     page_object=paginator.get_page(page_number)
#     context={
#         'title':'Projects',
#         'items': ['SQL', 'Power BI', 'Tableau', 'Dash', 'Django', 'Data Science', 'Classification'],
#         'proyek':proyeks,
#         'page_number':page_object
#     }
#     return render(request,'project/index.html',context)



class indexView(ListView):
    model = Proyek
    ordering = ['-tanggal']
    paginate_by = 6
    template_name = 'project/index.html'

    # Menambahkan extra_context langsung di dalam get_context_data
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Projects'
        context['item'] = ['Excel','SQL', 'Power-BI',
                           'Python','Streamlit', 'Django']
        return context

    def get_queryset(self):
        queryset = super().get_queryset()  # Mendapatkan queryset dasar dari ListView
        category = self.kwargs.get('category')

        if category and category != "ALL":
            queryset = queryset.filter(category__icontains=category)

        return queryset
    
    
    
    
def detail(request, slug):
    proyek = get_object_or_404(Proyek, slug=slug)
    context = {
        'title': 'Detail Projects',
        'proyek': proyek,
    }

    return render(request, 'project/detail.html', context)

services/views.py
from django.shortcuts import render
from .models import offer

# Create your views here.
def index(request):
    offers=offer.objects.all()
    context={
        'title':'Services',
        'offer':offers
    }
    return render(request,'services/index.html',context)

skill/views.py
from django.shortcuts import render
from .models import listskill

# Create your views here.
def index(request):
    skills=listskill.objects.all()
    context={
        'title':'Skill',
        'skill':skills
    }
    return render(request,'skill/index.html',context)

about/templates/about/index.html
{% extends 'base.html' %} {% load static %}
<!-- Css App About -->
{% block css_app %}
<link rel="stylesheet" href="{% static 'about/css/styles.css' %}" />
{% endblock %}

<!-- Content App About -->
{% block content_contents %}
<div class="content-header">
  <h3>{{title}}</h3>
</div>

<div class="content-content">
  <div class="description">
    <h3>Hi, Welcome</h3>
    <h2>I am Achmad Irfan</h2>
    <!-- Load Summary -->
    {% for item in summary %}
    <p>{{item.isi}}</p>
    {% endfor %}
  </div>
  <!-- Load Foto Profil -->
  <img src="{% static "about/img/foton.png" %}" alt="gambar" >
</div>
{% endblock %}

contact/templates/contact/index.html
{% extends 'base.html' %} {% load static %}
<!-- Css App About -->
{% block css_app %}
<link rel="stylesheet" href="{% static 'about/css/styles.css' %}" />
<link rel="stylesheet" href="{% static 'contact/css/styles.css' %}" />
{% endblock %}

<!-- Content App About -->
{% block content_contents %}
<div class="content-header">
  <h3>{{title}}</h3>
</div>
<div class="content-content">
  <div class="contact">
    <div class="contactItem">
      <i class="bx bx-current-location"></i>
      <h3>Location :</h3>
      <h4>Malang, Jawa Timur</h4>
    </div>
    <div class="contactItem">
      <i class="bx bxs-envelope"></i>
      <h3>Email :</h3>
      <h4>achmad.irfan1@yahoo.com</h4>
    </div>
    <div class="contactItem">
      <i class="bx bxs-phone-call"></i>
      <h3>Call :</h3>
      <h4>+62 821-1425-2524</h4>
    </div>
  </div>
</div>
{% endblock %}

project/templates/project/detail.html
{% extends 'about/index.html' %} {% load static %} {% block css_app %}
<link rel="stylesheet" href="{% static 'about/css/styles.css' %}" />
<link rel="stylesheet" href="{% static 'project/css/styles.css' %}" />
{% endblock %} {% block content_contents %}
<div class="detail">
  <div id="carouselExampleIndicators" class="carousel slide carousel-fade">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{{proyek.gambar.url}}" class="d-block w-100" alt="..." />
      </div>
      <div class="carousel-item">
        <img src="{{proyek.gambar3.url}}" class="d-block w-100" alt="..." />
      </div>
      <div class="carousel-item">
        <img src="{{proyek.gambar2.url}}" class="d-block w-100" alt="..." />
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <div class="infomation">
    <h4>Detail Project:</h4>
    <ul>
      <li><p>Nama : {{proyek.nama}}</p></li>
      <li><p>Category : {{ proyek.category|join:" , " }}</p></li>
      <li><p>Tanggal : {{proyek.tanggal}}</p></li>
      <li>
        <p>Output : <a href="{{proyek.output}}">Click Here</a></p>
      </li>
    </ul>
  </div>
</div>
<div class="embed">
  <h4>Project Visualization:</h4>
  {% if proyek.embed %}
  <div class="embed-wrapper">{{ proyek.embed|safe }}</div>
  {% endif %}
</div>
<button><a href="{% url 'app_project:project' %}">Back to Projects</a></button>
{% endblock %}

project/templates/project/index.html
{% extends 'about/index.html' %} {% load static %}
<!-- Css App About -->
{% block css_app %}
<link rel="stylesheet" href="{% static 'about/css/styles.css' %}" />
<link rel="stylesheet" href="{% static 'project/css/styles.css' %}" />
{% endblock %}

<!-- Content App About -->
{% block content_contents %}
<div class="content-header">
  <h3>{{title}}</h3>
</div>
<div class="content-content">
  <div class="classification">
    <a class="nav-link active" aria-current="page" href="{% url 'app_project:projects_category' 'ALL' %}" data-category="ALL">ALL</a>
    {% for item in item %}
    <div class="itemClassification">
      <a class="nav-link active" aria-current="page" href="{% url 'app_project:projects_category' item %}" data-category="{{ item }}">{{ item|upper }}</a>
    </div>
    {% endfor %}
  </div>
  <div class="thumbnail">
    {% for item in page_obj %}
    <div class="projectImage">
      <a href="{% url 'app_project:detail' item.slug %}">
        <img src="{{item.gambar.url}}" alt="alt" />
      </a>
      <h6>{{item.nama}}</h6>
    </div>
    {% endfor %}
  </div>
  <div class="paginator">
    <div class="leftPaginator">
      {% if is_paginated %} {% if page_obj.has_previous %}
      <a href="{% url 'app_project:project_page' page_obj.previous_page_number %}" title=""> &laquo</a>
      {% else %} <span>&laquo</span>
      {% endif %} {% endif %}
    </div>
    <div class="Page">
      {% for item in paginator.page_range %}
      <a href="{% url 'app_project:project_page' item %}" title="">{{item}}</a>
      {% endfor %}
    </div>
    <div class="RightPaginator">
      {% if is_paginated %} {% if page_obj.has_next %}
      <a href="{% url 'app_project:project_page' page_obj.next_page_number %}" title=""> &raquo</a>
      {% else %} <span>&raquo</span> {% endif %} {% endif %}
    </div>
  </div>
</div>
{% endblock %}

services/templates/services/index.html
{% extends 'base.html' %} {% load static %}
<!-- Css App About -->
{% block css_app %}
<link rel="stylesheet" href="{% static 'about/css/styles.css' %}" />
<link rel="stylesheet" href="{% static 'services/css/styles.css' %}" />
{% endblock %}

<!-- Content App About -->
{% block content_contents %}
<div class="content-header">
  <h3>{{title}}</h3>
</div>
<div class="content-content">
  <div class="serviceItemCol">
    {% for items in offer %}
    <div class="serviceItem">
      <i class="{{items.icon}}"></i>
      <h4 class="service">{{items.item}}</h4>
      <h5>{{items.desc}}</h5>
    </div>
    {% endfor %}
  </div>
  {% endblock %}
</div>

skill/templates/skill/index.html
{% extends 'base.html' %} {% load static %}
<!-- Css App About -->
{% block css_app %}
<link rel="stylesheet" href="{% static 'about/css/styles.css' %}" />
<link rel="stylesheet" href="{% static 'skill/css/styles.css' %}" />
{% endblock %}

<!-- Content App About -->
{% block content_contents %}
<div class="content-header">
  <h3>{{title}}</h3>
</div>
<div class="content-content">
  <ul class="skill">
    {% for skills in skill %}
    <li><img src="{{skills.image.url}}" alt="icon" /> {{skills.name_skill}}</li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>Achmad Irfan Afandi</title>
    <!-- Css Bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous" />
    <!-- End Css Bootstrap-->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <!-- Bootstrap Icon-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet" />

    <!-- EndBootstrap Icon-->
    <!-- Css App-->
    {% block css_app %} {% endblock %}
    <!-- End Css App-->
  </head>
  <body>
    {% include "snippets/navbar.html" %}

    <div class="content">
      <!-- Content -->
      {% block content_contents %} {% endblock %}
      <!-- End Content -->
    </div>
    <div class="footer">
      <p>© 2025 Designed By Achmad Irfan</p>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends "base.html" %} {% load static %} {% block content_contents %}
<img src="{% static 'img/foto1.png'%}" alt="" />

<div class="frontpage">
  <h3>Welcome,</h3>
  <h3>I am Achmad Irfan A.</h3>
  <h4>Data Analyst | Data Scientist | Python Developer</h4>
  <h2>Data is My World</h2>
  <button>
    <a href="{% static 'doc/cv.pdf' %}" download class="btn">Download CV <i class="bi bi-cloud-download-fill"></i></a>
  </button>
</div>
<div class="icon">
  <a href="https://www.linkedin.com/in/achmad-irfan-afandi-9661131a6/">
    <i class="bi bi-linkedin bi-lg custom-icon"> </i>
  </a>
  <a href="https://github.com/achmad-irfan">
    <i class="bi bi-github bi-lg custom-icon"> </i>
  </a>
  <a href="https://www.facebook.com/achmad.irfan.754">
    <i class="bi bi-facebook bi-lg custom-icon"> </i>
  </a>
  <a href="https://www.facebook.com/achmad.irfan.754">
    <i class="bi bi-twitter bi-lg custom-icon"> </i>
  </a>
  <a href="https://www.facebook.com/achmad.irfan.754">
    <i class="bi bi-instagram bi-lg custom-icon"> </i>
  </a>
</div>
{% endblock %}

templates/snippets/navbar.html
{% load static %}
<nav class="navbar ms-auto navbar-expand-md bg-dark-blue">
  <div class="container">
    <a class="navbar-brand" href="/"> <img src="{% static "img/logo.png"%}" alt="gambar"> </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
      <div class="navbar-nav mx-auto">
        <a class="nav-link" href="/">Home</a>
        <a class="nav-link" href="{% url 'app_about:about' %}">About</a>
        <a class="nav-link" href="{% url 'app_skill:skill' %}">Skill</a>
        <a class="nav-link" href="{% url 'app_project:project' %}">Projects</a>
        <a class="nav-link" href="{% url 'app_services:services' %}">Services</a>
        <a class="nav-link" href="{% url 'app_contact:contact' %}">Contact</a>
      </div>
    </div>
  </div>
</nav>